stages:
  - pre-build
  - build
  - post-build
  - test
  - post-test
  - coverage
  - extra 









verter-check:
  stage: post-build
  script:
    - cd materials/build/
    - sh run.sh > RESULT_VERTER.txt
    - cat RESULT_VERTER.txt
    - if [ $(grep "Style test result" RESULT_VERTER.txt | grep -oP "[0-9]") -eq 0 ]; then
    -   echo "| style failed" > VAR.txt
    - fi
    - if [ $(grep "Build result" RESULT_VERTER.txt | grep -oP "[0-9]") -eq 0 ]; then
    -  echo "$(cat VAR.txt) & build fail" > VAR.txt
    - fi
    - if [ $(grep "fail" VAR.txt | wc -l) -ne 0 ]; then 
    -  mv VAR.txt ../../src/VAR.txt
    -  exit 1
    - fi
    - echo "" >> VAR.txt
    - mv VAR.txt ../../src/VAR.txt
  needs:
    - building-job-lib
  allow_failure: true
  # artifacts:
  #   when: on_failure
  #   paths:
  #     - materials/build/RESULT_VERTER.txt
  #   expire_in: 5 days 



gcovr-job:
  stage: coverage
  script:
    - cd src
    - make gcov_report > TEMP_COV.txt
    - cat TEMP_COV.txt
    - grep -oP "Lines executed:\K[0-9]+" TEMP_COV.txt | grep -oP "[0-9]+" | tail -1 > VAR.txt
    - if [ $(grep . VAR.txt) -lt 95 ]; then #*
    -   echo "| Executed $(cat VAR.txt)% lines" > VAR.txt
    -   exit 1
    - fi
    - echo "| Executed $(cat VAR.txt)% lines" > VAR.txt
  needs:
    - building-job-lib
    - testing-job
  artifacts:
    when: always
    paths:
      - build/coverage
    expire_in: 5 days
  allow_failure: true
#* -can adjust how many % of lines may be not covered for successfull pass


clean-test-job:
  stage: extra
  script:
    - cd src
    - make s21_matrix.a
    - make clean
    - if ! git diff --quiet; then
    -   echo "| library st cleaning error" > VAR.txt
    -   exit 1
    - fi
    - make all
    - make clean
    - if ! git diff --quiet; then
    -   echo "| all st cleaning error" > VAR.txt
    -   exit 1
    - fi
    - make test
    - make clean
    - if ! git diff --quiet; then
    -   echo "| test st cleaning error" > VAR.txt
    -   exit 1
    - fi
    - make gcov_report
    - make clean
    - if ! git diff --quiet; then
    -   echo "| gcov st cleaning error" > VAR.txt
    -   exit 1
    - fi
  needs:
    - building-job-lib
    - testing-job
    - gcovr-job
  allow_failure: true
