name: 'Bot messaging'
description: 'This action sends CICD job and step info via telegram bot.'

inputs:
  bot_url:
    description: 'Telegram bot API token for url (BOT_GLADOS_URL)'
    required: true
  bot_id:
    description: 'Telegram chat ID (JO_CHAT_ID)'
    required: true
  job_status:
    description: 'Stores the status of the job'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Creating empty comment file
      shell: bash
      run: |
        if [ "$GITHUB_JOB" == "format-check-main" ] || [ "$GITHUB_JOB" == "format-check-tests" ]; then 
          echo "" > src/VAR.txt
        fi

    - name: Sending message
      shell: bash
      env:
        BOT_GLADOS_URL: ${{ inputs.bot_url }}
        JO_CHAT_ID: ${{ inputs.bot_id }}
        JOB_STATUS: ${{ inputs.job_status }}
      run: sh ./.github/bot_controls.sh

# Comment required jobs: 
#     cpp-check, 
#     valgrind-check (POST-TEST), 
#     building-lib-job, 
#     testing-job(TEST),
#     gcovr-job(COVERAGE), 
#     clean-test-job(EXTRA).
# Comment free jobs: 
#     format-check-main,
#     format-check-tests.     

