name: 'Bot messaging'
description: 'This action sends CICD job and step info via telegram bot.'
runs:
  using: 'composite'
  steps:
    - name: Creating empty comment file
      shell: bash
      run: |
        if [ "$GITHUB_JOB" == "format-check-main" ] || [ "$GITHUB_JOB" == "format-check-tests" ]; then 
          echo "" > src/VAR.txt
        fi

    - name: Sending message
      shell: bash
      run: sh ./bot_controls.sh

# Comment required jobs: 
#     cpp-check, 
#     building-job-lib, 
#     verter-check(POST-BUILD), 
#     testing-job(TEST),
#     valgrind-check (POST-TEST), 
#     gcovr-job(COVERAGE), 
#     clean-test-job(EXTRA).
# Comment free jobs: 
#     format-check-main,
#     format-check-tests.     

